# Generated by Django 5.0.4 on 2024-04-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(default=None, upload_to='restaurant_images/'),
            preserve_default=False,
        ),
    ]
